#%RAML 1.0 DataType
type: object
properties:
  user:
    type: object
    required: true
    properties:
      id?: string
      existing_user_id?: string
      existing_integration_id?: string
      existing_sis_user_id?: string
      trusted_account?: string
  login:
    type: object
    required: true
    properties:
      unique_id:
        type: string
        required: true
      password?: string
      sis_user_id?: string
      integration_id?: string
      authentication_provider_id?: string
      declared_user_type?:
        type: string
        enum: [administrative, observer, staff, student, student_other, teacher]
